import Foundation
@main struct Checks {
    static func main() {
        var p = VoiceActivationPolicy()
        for ambient in ["olá", "stars", "tarsiano", "como está o tempo", "Hi Carlos", "Hi Thaís", "Karen", ""] {
            assert(p.consume(ambient) == .ignore)
        }
        assert(p.consume("Ei, TARS!") == .acknowledge)
        assert(p.consume("Como está o tempo?") == .request("Como está o tempo?"))
        assert(p.consume("outra conversa") == .ignore)
        assert(p.consume("TARS, olá") == .request("olá"))
        assert(p.consume("TARS") == .acknowledge)
        assert(p.consume("") == .ignore)
        assert(p.consume("fala ambiente") == .ignore)
        assert(p.consume("TARS") == .acknowledge)
        p.failed()
        assert(!p.awaitingRequest)
        assert(p.consume("não repetir pedido antigo") == .ignore)
        for _ in 0..<20 { p.failed() }
        assert(p.retrySeconds == 30)
        p.reset()
        assert(p.retrySeconds == 0.6 && !p.awaitingRequest)
        assert(p.consume("tArS: diga olá") == .request("diga olá"))
        assert(p.consume("Hey TARS!") == .acknowledge)
        assert(p.consume("What time is it?") == .request("What time is it?"))
        assert(p.consume("TARS, qual é a capital do Brasil?") == .request("qual é a capital do Brasil?"))
        assert(p.consume("TARS, tell me a joke") == .request("tell me a joke"))
        assert(p.consume("background conversation") == .ignore)
        var conversation = VoiceActivationPolicy()
        assert(conversation.consume("hello", now: 100) == .ignore)
        conversation.replyFinished(now: 100)
        assert(conversation.consume("continue in English", now: 129.9) == .request("continue in English"))
        assert(conversation.consume("uninvited second phrase", now: 129.95) == .ignore)
        conversation.replyFinished(now: 200)
        assert(conversation.consume("expired", now: 230) == .ignore)
        assert(conversation.consume("clock reversed", now: 199) == .ignore)
        conversation.failed()
        assert(conversation.consume("after error", now: 210) == .ignore)
        conversation.replyFinished(now: 300)
        conversation.reset()
        assert(conversation.consume("after suspension", now: 301) == .ignore)
        conversation.replyFinished(now: 400)
        assert(conversation.consume("", now: 401) == .ignore)
        assert(conversation.consume("after silence", now: 402) == .ignore)
        var budget = OnlineVoiceTrialBudget()
        assert(!budget.available(now: 100))
        budget.begin(now: 100)
        assert(!budget.available(now: 99))
        for _ in 0..<6 { assert(budget.reserveUpload(now: 110)) }
        assert(!budget.reserveUpload(now: 110))
        budget.begin(now: 120)
        assert(!budget.available(now: 120))
        var expiry = OnlineVoiceTrialBudget()
        expiry.begin(now: 100)
        assert(expiry.available(now: 279))
        assert(!expiry.reserveUpload(now: 280))
        let silence = VoiceCaptureWindow(now: 100)
        assert(silence.decision(now: 114.99) == .keepListening)
        assert(silence.decision(now: 115) == .discard)
        var phrase = VoiceCaptureWindow(now: 100)
        phrase.observeVoice(now: 102)
        assert(phrase.decision(now: 104.39) == .keepListening)
        assert(phrase.decision(now: 104.5) == .finish)
        var continuous = VoiceCaptureWindow(now: 100)
        for second in 100..<120 {
            continuous.observeVoice(now: Double(second))
            assert(continuous.decision(now: Double(second)) == .keepListening)
        }
        assert(continuous.decision(now: 120) == .finish)
        assert(silence.decision(now: 103, hasTranscript: true) == .finish)
        assert(silence.decision(now: 99) == .discard)
        assert(silence.decision(now: .infinity) == .discard)
        assert(silence.decision(now: .nan) == .discard)
        var invalid = VoiceCaptureWindow(now: 100)
        invalid.observeVoice(now: 99)
        assert(invalid.decision(now: 101) == .discard)
        assert(VoiceCaptureWindow(now: .nan).decision(now: 101) == .discard)
        // A new capture gets fresh timing, not speech from the previous question.
        assert(VoiceCaptureWindow(now: 200).decision(now: 203) == .keepListening)
        print("Voice activation PT/EN, capture deadlines and bounded online trial checks PASS")
    }
}
